//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_MagLink
{
    using System;
    using System.Collections.Generic;
    
    public partial class AckMessage
    {
        public string FieldName { get; set; }
        public string Segment { get; set; }
        public Nullable<long> Sequence { get; set; }
        public long ID { get; set; }
        public string EventType { get; set; }
        public string ContentOut { get; set; }
        public Nullable<long> Order { get; set; }
    }
}
