//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_MagLink
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message_History
    {
        public System.DateTime DateTime { get; set; }
        public string messageid { get; set; }
        public long mhistID { get; set; }
        public string PatID { get; set; }
        public string PatName { get; set; }
        public string Message { get; set; }
    }
}
