//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_MagLink
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MagLink_engineEntities : DbContext
    {
        public MagLink_engineEntities()
            : base("name=MagLink_engineEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Pref> Prefs { get; set; }
        public virtual DbSet<Queue> Queues { get; set; }
        public virtual DbSet<Registry> Registries { get; set; }
        public virtual DbSet<AckMessage> AckMessages { get; set; }
        public virtual DbSet<Message_History> Message_History { get; set; }
    }
}
