//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_MagLink
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pref
    {
        public string PrefName { get; set; }
        public long ID { get; set; }
        public string Help { get; set; }
        public string Details { get; set; }
    }
}
