//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_MagLink
{
    using System;
    using System.Collections.Generic;
    
    public partial class Queue
    {
        public string MessageID { get; set; }
        public string Message { get; set; }
        public string Type { get; set; }
        public string PatientMRN { get; set; }
        public Nullable<bool> Sent { get; set; }
        public Nullable<System.DateTime> SentDateTime { get; set; }
        public Nullable<bool> Garbage { get; set; }
        public Nullable<long> Count { get; set; }
        public long ID { get; set; }
    }
}
