//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_MagLink
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registry
    {
        public long ID { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> HeartBeat { get; set; }
        public string ErrorState { get; set; }
        public string ErrorMessage { get; set; }
        public Nullable<System.DateTime> LastMessage { get; set; }
    }
}
